apiVersion: v1
kind: Service
metadata:
  name: {{ template "k8s-minecraft.fullname" . }}
  labels:
    app: {{ template "k8s-minecraft.name" . }}
    chart: {{ template "k8s-minecraft.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: {{ .Values.service.name }}
    - port: {{ .Values.monitor.port }}
      targetPort: {{ .Values.monitor.port }}
      nodePort: {{ .Values.monitor.nodePort }}
      protocol: TCP
      name: {{ .Values.monitor.name }}
  selector:
    app: {{ template "k8s-minecraft.name" . }}
    release: {{ .Release.Name }}
