apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-pv
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
  labels:
    app: minecraft
    appid: portal
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/pv
  storageClassName: standard
