{
 "title": "Players",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "player",
    "label": "Player",
    "query": "label_values(mc_player_online, name)"
   },
   {
    "name": "statistic",
    "label": "Statistic",
    "query": "label_values(mc_player_statistic,statistic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Currently Online",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(mc_player_online{name=~\"$player\"}) by (name)"
    }
   ]
  },
  {
   "title": "$statistic over time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_player_statistic{player_name=~\"$player\", statistic=~\"$statistic\"}",
     "legendFormat": "{{player_name}}: {{statistic}}"
    }
   ]
  },
  {
   "title": "$statistic by player",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "mc_player_statistic{player_name=~\"$player\", statistic=\"$statistic\"}",
     "legendFormat": "{{player_name}}: {{statistic}}"
    }
   ]
  }
 ]
}